#target : Dependencies
#<TAB>commands

Build : project_main.c TicTacToe.c 
        gcc project_main.c TicTacToe.c TicTacToe.out
Run : TicTacToe.out
	   ./TicTacToe.out
Clean : 
		rm -rf * .o *.out *.i *.s
