#target : Dependencies
#<TAB>commands

Build : project_main.c SmartBlindAssistant.c 
        gcc project_main.c SmartBlindAssistant.c SmartBlindAssistant.out
Run : SmartBlindAssistant.out
	   ./SmartBlindAssistant.out
Clean : 
		rm -rf * .o *.out *.i *.s
