#target : Dependencies
#<TAB>commands

Built : project_main.c Smart Blind Assistant.c test_Smart Blind Assistant.c unity.c
        gcc project_main.c Smart Blind Assistant.c test_Smart Blind Assistant.c unity.c -o Smart Blind Assistant.out
Run : Smart Blind Assistant.out
                 ./Smart Blind Assistant.out
Clean :
                            rm -rf *  .o *.out *.i *.s
